@Library("shared-library") _
pipeline {
    agent any
    //docker { image 'shivam139/jenkins-agent-ubuntu:v2' args '--user root -v /var/run/docker.sock:/var/run/docker.sock' }

    environment {
        IMAGE_TAG = "v${env.BUILD_NUMBER}"
    }

    stages {
        stage('checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/shivampawar777/test_sapp.git' 
                sh 'echo passed...'
            }
        }
        stage('Build & push docker image') {
            environment {
                DockerFile_path = "CI/Python-app/"
            }
            
            steps {
                echo 'Building the docker image and pushing to the dockerHub...'
                dockerImage()
            }
        }
        stage('Update deployment manifest') {
            environment {
                GITHUB_USER = "shivampawar777"
                GITHUB_REPO = "test_sapp"
                deployment_file_path = "CD/Deployment-Manifest/deployment.yml"
            }
            steps {
                updateDeploymentManifest() 
            }
        }
    }
}